config/routes.rb
Crowdfund::Application.routes.draw do
 root 'projects#index'
 resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base

	def self.accepting
		where('pledging_ends_on > ?', Time.now)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.accepting
	end

	def show
		@project = Project.find(params[:id])

	rescue ActiveRecord::RecordNotFound
		redirect_to :action => 'index'
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update 
		@project = Project.find(params[:id])
		@project.update(project_params)
		redirect_to @project
	end

	def new
	@project = Project.new 
	end

	def create
		@project = Project.new(project_params)
		@project.save
		redirect_to @project
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to	projects_path
	end


	private

	def project_params
		params.require(:project).permit(
			:name, :description, :target_pledge_amount, :website, :pledging_ends_on)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def wording(project)
		if project.pledging_ends_on > Time.now
			content_tag(:strong, time_ago_in_words(project.pledging_ends_on) + " from now") 
		else 
			content_tag(:strong, 'Project Funding Finished')
		end
	end

	def image(project)
		if project.image_file_name.blank?
			image_tag 'placeholder.jpg', size: '100'
		else
			image_tag project.image_file_name, size: '100'
		end
	end
end

app/views/layouts/_footer.html.erb
<footer style='text-align:center; background: lightgray; padding: 5px; color: #237CBE;'>
	<p>Copyright &copy; <%= link_to 'Zack Fisch', 'http://zfisch.com' %>
	</p>
</footer>

app/views/layouts/_header.html.erb
<header>
		<h1 style='background: #33A1C9;'>Crowdfundr</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside style='float:right; width: 200px; background: lightgray;'>
		<nav>
			<ul style='list-style-type: none; float: right;'>
				<li> 
					<%= link_to 'All Projects', projects_path %> 
				</li>
				<li> 
					<%= link_to 'New Project', new_project_path %>
				</li>
			</ul>
		</nav>
	</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfund</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

	<%= render 'layouts/sidebar' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/projects/edit.html.erb
<h1>Editing <%= @project.name %></h1>

<%= form_for(@project) do |f| %>
	<p>
		<%= f.label :name %>
	</p>
	<p>
		<%= f.text_field :name, size: 30 %>
	</p>

	<p>
		<%= f.label :description %>
	</p>
	<p>
		<%= f.text_area :description, cols: 40, rows: 7 %>
	</p>

	<p>
		<%= f.label :target_pledge_amount %>
	</p>
	<p>
		<%= f.number_field :target_pledge_amount %>
	</p>

	<p>
		<%= f.label :website %>
	</p>
	<p>
		<%= f.text_field :website %>
	</p>

	<p>
		<%= f.label :pledging_ends_on %>
	</p>
	<p>
		<%= f.date_field :pledging_ends_on %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/projects/index.html.erb
<h1><%= pluralize(@projects.length, 'Project') %></h1>

<h3><%= link_to 'New Project', new_project_path %></h3>
	<% @projects.each do |project| %>
	<h3>
		<%= link_to(project.name, project)  %>
	</h3>  
	<p>
		<%= truncate(project.description, length: 150, separator: ' ') %> 
	</p>
	<p>
		<%= number_to_currency(project.target_pledge_amount) %>
	</p>
	<p>
		<%= project.website %> 
	</p>
	<p>
		Funding Ends: <%= wording(project) %>
	</p>

	<p>
		<%= image(project) %>
	</p>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for(@project) do |f| %>
	<p>
		<%= f.label :name %>:
		<%= f.text_field :name, size: 30 %>
	</p>

	<p>
		<%= f.label :description %>:
		<%= f.text_area :description, cols: 40, rows: 7 %>
	</p>

	<p>
		<%= f.label :target_pledge_amount %>:
		<%= f.number_field :target_pledge_amount %>
	</p>

	<p>
		<%= f.label :website %>:
		<%= f.text_field :website %>
	</p>

	<p>
		<%= f.label :pledging_ends_on %>:
		<%= f.date_field :pledging_ends_on %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/projects/show.html.erb
	<article>
		<header>
			<h2><%= @project.name %></h2>
		</header>
			<p>
				Description: <%= @project.description %>
			</p>
				<p>
					Target Raise: <%= @project.target_pledge_amount %>
				</p>
				<p>
					Website: <%= @project.website %>
				</p>
				<p>
					Funding Ends: <%= wording(@project) %>
				</p>

				<p>
					<%= image(@project) %>
				</p>
	</article>

<%= link_to 'Edit', edit_project_path(@project) %> | 
<%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} %>